version: '3.8'
services:
 bud-api:
    container_name: buddyrewrd-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
    env_file:
      - .env